name: CI Pipeline

# 1) When to run
on:
  push:
    branches: [main, mvp-flask]
  pull_request:
    branches: [main, mvp-flask]

# 2) Jobs definition
jobs:
  test:
    name: Run Tests & Lint
    runs-on: ubuntu-latest

    steps:
      # 2.1 Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2.2 Set up Python
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.3"

      # 2.3 Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 2.4 Run pre-commit checks
      - name: Run pre-commit hooks
        run: |
          pre-commit run --all-files

      # 2.5 Run your test suite
      - name: Run unit tests
        env:
          FLASK_CONFIG: testing
        run: |
          python -m unittest discover tests
